### ISSUE TITLE
カードPDFができていない件

### ISSUE THREAD

**Issue by alecrem** [kanjifanclub/kanjifanclub.alecrem.com#5]
最初は省略可？

**Comment by kogatakahiro** [comment]
PDFには白黒のイラストいれるの？？

**Comment by alecrem** [comment]
どうする？どうやって有料版と違うようにする？

1. 白黒
1. イラストなし
1. カラーそのまま？

イラストなしはやりすぎかな。イラストはちゃんとみてほしいな。

カラー無料配布のデメリットは？

1. 買ってもいいという人が買わなくなる可能性: でも、コピーを作る手間とかを考えて、カラーのPDFをもらっても自分用のお試し版は白黒にすると思う
2. 海賊版: 贅沢な問題

@kogatakahiro どっちがいいと思う？僕は今のところ、イラストが一応なんらかの形で乗っていたほうがいいと思うだけ。カラーに関しては特にこだわりがないな。
